= Master programming. pass:[<br>] Лекция №2 (Работа с git)
:author: Игорь Шаронов
:date: 2018-09-09
:lang: ru
:numbered:

== Система контроля версий git

=== Основные ссылки

* https://git-scm.com[] -- основной сайт с документацией по git
* https://try.github.io[] -- онлайн путеводитель по git-у
* https://githowto.com/ru[] -- ещё один путеводитель
* https://learngitbranching.js.org/?demo[] -- попробовать git в реалтайме

=== Предыстория

* `diff` -- утилита для выяснения различий
+
[source,diff]
----
$ diff -u lecture-1.html lecture-2.html | head -n 20
--- lecture-1.html 2018-02-25 14:49:23.665411221 +0300
+++ lecture-2.html 2018-02-25 14:49:23.842322309 +0300
@@ -4,7 +4,7 @@
   <meta name="generator" content="pandoc">
   <meta name="author" content="Игорь Шаронов">
-  <meta name="dcterms.date" content="2018-01-15">
+  <meta name="dcterms.date" content="2018-02-18">
   <title>Master programming</title>
   <meta name="apple-mobile-web-app-capable" content="yes">
----
* `patch` -- обратное действие `diff` (патч)
* конфликты
+
----
<<<<<<< LOCAL:sample.txt
lines from the original file
======= REMOTE:sample.txt
new lines from the patch
>>>>>>>
----

== Как устроен git

=== Внутренности git-а

* Директория .git/
** .git/objects/ -- пулл объектов
** .git/refs/ -- указатели
** .git/HEAD -- указатель текущей ветки
* git -- файловая система ассоциативного типа
* Виды объектов: blob, tree, commit, tag
* Виды ссылок: branch, tag, remotes
* Коммит: tree-объект, автор, коммитер, сообщение, parent

=== Хеш-суммы

* crc32 (пример: F6DE2FEA)
* md5 (пример: C43FE3F8445CDB869C6A6DA9AEA90B21)
* sha-1 (пример: 7DD987F846400079F4B03C058365A4869047B4A0)
* sha-2: sha-224, sha-256, sha-384, sha-512 (пример: CA737F1014A48F4C0B6DD43CB177B0AFD9E5169367544C494011E3317DBF9A509CB1E5DC1E85A941BBEE3D7F2AFBC9B1)
* Быстрая идентификация сообщения/файла/пароля
+
[source,bash]
----
$ echo -n 'Master programming' | md5sum -
01e171232a1aa47e9fd2ae0530782b1f  -
$ echo -n 'master programming' | md5sum -
e774d0115e01e1b735a7a1a9a3a85f09  -
----
* Коллизии хешей

== Повседневное использование

=== Основные команды

* `git status`: unstaged, staged, committed
* `git add <file>` -- добавление `file` в `staged`
* `git checkout <name>` -- переход на ветку `name`
* `git checkout -b <name>` -- создание новой ветки `name`
* `git checkout -- <file>` -- отменить все изменения файла `file`
* `git reset [<commit>|<branch>]` -- перевести изменения из `committed` в состояние `unstaged`
* `git reset --hard` -- отменить все изменения (потеря данных)
* `git push [<remote>]` -- загрузка изменений на сервер `remote`
* `git push --force` -- принудительная загрузка изменений (потеря данных)
* `git diff [<commit>]` -- просмотр изменений

=== Пример №1: добавление нескольких remote

[source,bash]
----
$ git clone git@github.com:cvlabmiet/master-programming
$ cd master-programming
master-programming $ git remote add miet git@git.miet.ru:cvlab/master-programming
master-programming $ git push miet master:master
----

[source,bash]
----
(lecture-2 *+) $ git st
On branch lecture-2
Changes to be committed:
(use "git reset HEAD <file>..." to unstage)
    modified:   CMakeLists.txt
    modified:   lecture-2.adoc
Changes not staged for commit:
    (use "git add <file>..." to update what will be committed)
    (use "git checkout -- <file>..." to discard changes in working directory)
    modified:   lecture-2.adoc
----

=== Пример №2: создание локального репозитория

[cols="2*a",frame="none",grid="none"]
|===
|
.На сервере
[source,bash]
----
$ mkdir /tmp/server
$ git init --bare /tmp/server/repo
$ cd /tmp/server/repo/
repo (BARE:master) $ ls
branches  config  description  HEAD  hooks  info  objects  refs
----
|
.На клиенте
[source,bash]
----
$ git init /tmp/repo
$ cd /tmp/repo
repo (master#) $ echo 'Empty repo' > README.md
repo (master#) $ git add README.md
repo (master#) $ git ci -am "Initial commit"
repo (master) $ git remote add origin /tmp/server/repo
repo (master) $ git push origin master:master
----
|===

=== Пример №3: сравнение с origin/master

[source,bash]
----
$ git fetch origin
$ git diff master origin/master
$ git show origin/master:lecture-3.md | less
$ git co origin/master -b new-feature
----

== Объединение веток

=== Разрешение конфликтов

* LOCAL -- локальные изменения текущей ветки
* REMOTE -- изменения на сервере
* BASE -- общий предок LOCAL и REMOTE
* MERGED -- автоматическое разрешение конфликта
* merge -- это тоже коммит
* Утилиты для разрешения конфликтов: vimdiff, kdiff3, meld, tortoisemerge

----
┌───────┬──────┬────────┐   ┌────────┬────────┐
│ LOCAL │ BASE │ REMOTE │   │        │        │
├───────┴──────┴────────┤   │ MERGED │ REMOTE │
│        MERGED         │   │        │        │
└───────────────────────┘   └────────┴────────┘
----

=== Стратегии объединения веток

[cols="a,a",frame="none",grid="none"]
|===
|
Хотим объединить ветки topic и master:
----
      A---B---C topic
     /
D---E---F---G master
----
|
* merge no-fast-forward (`git merge --no-ff`):
+
----
      A---B---C topic
     /         \
D---E---F---G---H master
----
* merge fast-forward (`git merge --ff`):
+
----
D---E-A-F-B-G-C master
----
* merge squash (`git merge --squash`):
+
----
D---E---F---G---T master
----
* rebase (`git rebase master`):
+
----
              A---B---C topic
             /
D---E---F---G master
----
|===
