# vim: ts=2 sw=2

name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable:nixpkgs-overlays=https://api.github.com/repos/igsha/nix-overlays/tarball/031c8e1
    - name: Build target
      run: |
        cmake -B build -GNinja
        cmake --build build
        mkdir deploy
        cd build
        cp ./**/*.html ./*.html --parents -t ../deploy/
      shell: env nix-shell --run "bash -e {0}"
    - uses: JamesIves/github-pages-deploy-action@releases/v3
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: deploy
