# vim: ts=2 sw=2

name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v6
    - name: Build target
      run: |
        cmake -B build
        cmake --build build -j
        mkdir deploy
        cp build/**/*.html build/*.html deploy/
      shell: env nix-shell
        -I nixpkgs=channel:nixos-19.09
        -I nixpkgs-overlays=https://api.github.com/repos/igsha/nix-overlays/tarball/master
        --run "bash -e {0}"
    - uses: JamesIves/github-pages-deploy-action@releases/v3
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: deploy
